// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zunrbufufmeiacywufoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bnJidWZ1Zm1laWFjeXd1Zm9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTA3NDgsImV4cCI6MjA2OTM4Njc0OH0.s5yJDAgHLTW0Yv_2II9dosKsWJhBAJP8sg6Jklhw1_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});